INSERT INTO product_group (name) VALUES
    ('Befestigungsmaterialien'),
    ('Werkzeuge'),
    ('Elektronik'),
    ('Büro'),
    ('Wohnen'),
    ('Sport'),
    ('Mode'),
    ('Schmuck'),
    ('Tierbedarf'),
    ('Lebensmittel'),
    ('Spielwaren'),
    ('Gruppe 12'),
    ('Gruppe 13'),
    ('Gruppe 14'),
    ('Gruppe 15');

INSERT INTO product_class (name, product_group) VALUES
    ('Schrauben', 1),
    ('Nägel', 1),
    ('Klebstoffe', 1),
    ('Scharniere', 1),
    ('Hämmer', 2),
    ('Bohrmaschinen', 2),
    ('Schraubschlüssel', 2),
    ('Zangen', 2),
    ('Lampen', 3),
    ('Kabel', 3),
    ('Schalter', 3),
    ('Batterien', 3),
    ('Stühle', 4),
    ('Tische', 4),
    ('Kommunikation', 4),
    ('Kategorie 4 Büro', 4),
    ('Möbel', 5),
    ('Lichter', 5),
    ('Dekoration', 5),
    ('Kategorie 4 Wohnen', 5),
    ('Schuhe', 6),
    ('Kleidung', 6),
    ('Geräte', 6),
    ('Rucksäcke', 6),
    ('Schuhe', 7),
    ('Oberteile', 7),
    ('Jacken', 7),
    ('Hosen', 7),
    ('Ketten', 8),
    ('Uhren', 8),
    ('Ohrringe', 8),
    ('Ringe', 8),
    ('Futter', 9),
    ('Spielzeuge', 9),
    ('Transportboxen', 9),
    ('Betten', 9),
    ('Pasta', 10),
    ('Brot', 10),
    ('Saucen', 10),
    ('Gemüse', 10),
    ('LEGO', 11),
    ('Playmobil', 11),
    ('Kleinkinder', 11),
    ('Kategorie 4 Spielzeuge', 11),
    ('Kategorie 1 Gruppe 12', 12),
    ('Kategorie 2 Gruppe 12', 12),
    ('Kategorie 3 Gruppe 12', 12),
    ('Kategorie 4 Gruppe 12', 12),
    ('Kategorie 1 Gruppe 13', 13),
    ('Kategorie 2 Gruppe 13', 13),
    ('Kategorie 3 Gruppe 13', 13),
    ('Kategorie 4 Gruppe 13', 13),
    ('Kategorie 1 Gruppe 14', 14),
    ('Kategorie 2 Gruppe 14', 14),
    ('Kategorie 3 Gruppe 14', 14),
    ('Kategorie 4 Gruppe 14', 14),
    ('Kategorie 1 Gruppe 15', 15),
    ('Kategorie 2 Gruppe 15', 15),
    ('Kategorie 3 Gruppe 15', 15),
    ('Kategorie 4 Gruppe 15', 15);

INSERT INTO product_family(name, product_class) VALUES
    ('Holzschrauben', 1),
    ('Metallschrauben', 1),
    ('Familie 1 Nägel', 2),
    ('Familie 2 Nägel', 2),
    ('Familie 1 Klebstoffe', 3),
    ('Familie 2 Klebstoffe', 3),
    ('Familie 1 Scharniere', 4),
    ('Familie 2 Scharniere', 4),
    ('Familie 1 Hämmer', 5),
    ('Familie 2 Hämmer', 5),
    ('Familie 1 Bohrmaschinen', 6),
    ('Familie 2 Bohrmaschinen', 6),
    ('Familie 1 Schraubschlüssel', 7),
    ('Familie 2 Schraubschlüssel', 7),
    ('Familie 1 Zangen', 8),
    ('Familie 2 Zangen', 8),
    ('Familie 1 Lampen', 9),
    ('Familie 2 Lampen', 9),
    ('Familie 1 Kabel', 10),
    ('Familie 2 Kabel', 10),
    ('Familie 1 Schalter', 11),
    ('Familie 2 Schalter', 11),
    ('Familie 1 Batterien', 12),
    ('Familie 2 Batterien', 12),
    ('Familie 1 Stühle', 13),
    ('Familie 2 Stühle', 13),
    ('Familie 1 Tische', 14),
    ('Familie 2 Tische', 14),
    ('Familie 1 Kommunikation', 15),
    ('Familie 2 Kommunikation', 15),
    ('Familie 1 Kategorie 4 Büro', 16),
    ('Familie 2 Kategorie 4 Büro', 16),
    ('Familie 1 Möbel', 17),
    ('Familie 2 Möbel', 17),
    ('Familie 1 Lichter', 18),
    ('Familie 2 Lichter', 18),
    ('Familie 1 Dekoration', 19),
    ('Familie 2 Dekoration', 19),
    ('Familie 1 Kategorie 4 Wohnen', 20),
    ('Familie 2 Kategorie 4 Wohnen', 20),
    ('Familie 1 Schuhe', 21),
    ('Familie 2 Schuhe', 21),
    ('Familie 1 Kleidung', 22),
    ('Familie 2 Kleidung', 22),
    ('Familie 1 Geräte', 23),
    ('Familie 2 Geräte', 23),
    ('Familie 1 Rucksäcke', 24),
    ('Familie 2 Rucksäcke', 24),
    ('Familie 1 Schuhe', 25),
    ('Familie 2 Schuhe', 25),
    ('Familie 1 Oberteile', 26),
    ('Familie 2 Oberteile', 26),
    ('Familie 1 Jacken', 27),
    ('Familie 2 Jacken', 27),
    ('Familie 1 Hosen', 28),
    ('Familie 2 Hosen', 28),
    ('Familie 1 Ketten', 29),
    ('Familie 2 Ketten', 29),
    ('Familie 1 Uhren', 30),
    ('Familie 2 Uhren', 30),
    ('Familie 1 Ohrringe', 31),
    ('Familie 2 Ohrringe', 31),
    ('Familie 1 Ringe', 32),
    ('Familie 2 Ringe', 32),
    ('Familie 1 Futter', 33),
    ('Familie 2 Futter', 33),
    ('Familie 1 Spielzeuge', 34),
    ('Familie 2 Spielzeuge', 34),
    ('Familie 1 Transportboxen', 35),
    ('Familie 2 Transportboxen', 35),
    ('Familie 1 Betten', 36),
    ('Familie 2 Betten', 36),
    ('Familie 1 Pasta', 37),
    ('Familie 2 Pasta', 37),
    ('Familie 1 Brot', 38),
    ('Familie 2 Brot', 38),
    ('Familie 1 Saucen', 39),
    ('Familie 2 Saucen', 39),
    ('Familie 1 Gemüse', 40),
    ('Familie 2 Gemüse', 40),
    ('Familie 1 LEGO', 41),
    ('Familie 2 LEGO', 41),
    ('Familie 1 Playmobil', 42),
    ('Familie 2 Playmobil', 42),
    ('Familie 1 Kleinkinder', 43),
    ('Familie 2 Kleinkinder', 43),
    ('Familie 1 Kategorie 4 Spielzeuge', 44),
    ('Familie 2 Kategorie 4 Spielzeuge', 44),
    ('Familie 1 Kategorie 1 Gruppe 12', 45),
    ('Familie 1 Kategorie 1 Gruppe 12', 45),
    ('Familie 1 Kategorie 2 Gruppe 12', 46),
    ('Familie 2 Kategorie 2 Gruppe 12', 46),
    ('Familie 1 Kategorie 3 Gruppe 12', 47),
    ('Familie 2 Kategorie 3 Gruppe 12', 47),
    ('Familie 1 Kategorie 4 Gruppe 12', 48),
    ('Familie 2 Kategorie 4 Gruppe 12', 48),
    ('Familie 1 Kategorie 1 Gruppe 13', 49),
    ('Familie 2 Kategorie 1 Gruppe 13', 49),
    ('Familie 1 Kategorie 2 Gruppe 13', 50),
    ('Familie 2 Kategorie 2 Gruppe 13', 50),
    ('Familie 1 Kategorie 3 Gruppe 13', 51),
    ('Familie 2 Kategorie 3 Gruppe 13', 51),
    ('Familie 1 Kategorie 4 Gruppe 13', 52),
    ('Familie 2 Kategorie 4 Gruppe 13', 52),
    ('Familie 1 Kategorie 1 Gruppe 14', 53),
    ('Familie 2 Kategorie 1 Gruppe 14', 53),
    ('Familie 1 Kategorie 2 Gruppe 14', 54),
    ('Familie 2 Kategorie 2 Gruppe 14', 54),
    ('Familie 1 Kategorie 3 Gruppe 14', 55),
    ('Familie 2 Kategorie 3 Gruppe 14', 55),
    ('Familie 1 Kategorie 4 Gruppe 14', 56),
    ('Familie 2 Kategorie 4 Gruppe 14', 56),
    ('Familie 1 Kategorie 1 Gruppe 15', 57),
    ('Familie 2 Kategorie 1 Gruppe 15', 57),
    ('Familie 1 Kategorie 2 Gruppe 15', 58),
    ('Familie 2 Kategorie 2 Gruppe 15', 58),
    ('Familie 1 Kategorie 3 Gruppe 15', 59),
    ('Familie 2 Kategorie 3 Gruppe 15', 59),
    ('Familie 1 Kategorie 4 Gruppe 15', 60),
    ('Familie 2 Kategorie 4 Gruppe 15', 60);




